GET  https://mock-api-json-server-ooya.onrender.com/Users

###

DELETE  https://mock-api-json-server-ooya.onrender.com/Users/13
Content-Type: application/json

###
PATCH  https://mock-api-json-server-ooya.onrender.com/Users/8
Content-Type: application/json

{
    
    "username":"rutuja",
    "password":"rutuja"
}

###
POST https://mock-api-json-server-ooya.onrender.com/Users
Content-Type: application/json

 {
    "username": "astha",
    "password": "Astha@1432",
    "firstname": "Astha",
    "lastname": "gfhf",
    "email": "astha@gmail.com"
  }

### filter by id
GET https://mock-api-json-server-ooya.onrender.com/Users
#fetch(`${baseUsl}`,{
# method:"POST",
# body:JSON.stringify(formdata),
# headers:{
#     "content-type":"application/json"
# }, 
# })
# .then((res)=>{
# return res.json();
# })
# .then((data)=>{
# console.log(data)
# myUserData.push(data)
# }).catch((err)=>{
#     console.log(err)
# })