GET  http://localhost:3000/users

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "password": "Abhi@123",
    "firstname": "Abhi",
    "lastname": "Raghatate",
    "email": "abhi@gmail.com"
  }

###
PATCH  http://localhost:3000/AdminUsers/10
Content-Type: application/json

{
    
    "username":"rutuja",
    "password":"rutuja"
}

###
POST http://localhost:3000/AdminUsers
Content-Type: application/json

{
    
    "username":"rushi",
    "password":"rushi"
}

### filter by id
GET https://busy-lime-gecko-cape.cyclic.app/localUsers
#fetch(`${baseUsl}`,{
# method:"POST",
# body:JSON.stringify(formdata),
# headers:{
#     "content-type":"application/json"
# }, 
# })
# .then((res)=>{
# return res.json();
# })
# .then((data)=>{
# console.log(data)
# myUserData.push(data)
# }).catch((err)=>{
#     console.log(err)
# })